/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as MarketResearchRouteImport } from './routes/market-research'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosVideoIdRouteImport } from './routes/videos_.$videoId'
import { ServerRoute as ApiChatServerRouteImport } from './routes/api.chat'

const rootServerRouteImport = createServerRootRoute()

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketResearchRoute = MarketResearchRouteImport.update({
  id: '/market-research',
  path: '/market-research',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos_/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatServerRoute = ApiChatServerRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/market-research': typeof MarketResearchRoute
  '/videos': typeof VideosRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/market-research': typeof MarketResearchRoute
  '/videos': typeof VideosRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/market-research': typeof MarketResearchRoute
  '/videos': typeof VideosRoute
  '/videos_/$videoId': typeof VideosVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/market-research' | '/videos' | '/videos/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/market-research' | '/videos' | '/videos/$videoId'
  id: '__root__' | '/' | '/market-research' | '/videos' | '/videos_/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketResearchRoute: typeof MarketResearchRoute
  VideosRoute: typeof VideosRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
}
export interface FileServerRoutesByFullPath {
  '/api/chat': typeof ApiChatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/chat': typeof ApiChatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/chat': typeof ApiChatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/chat'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/chat'
  id: '__root__' | '/api/chat'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiChatServerRoute: typeof ApiChatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-research': {
      id: '/market-research'
      path: '/market-research'
      fullPath: '/market-research'
      preLoaderRoute: typeof MarketResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos_/$videoId': {
      id: '/videos_/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketResearchRoute: MarketResearchRoute,
  VideosRoute: VideosRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiChatServerRoute: ApiChatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
